apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-zpspytwn
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-zpspytwn:0eb2b37e1efafdb65d34e4f256481e99112ac34f@sha256:235738b7b4090a4d7f92750da22160534f64e1e0f76b8f5b1fdac516f6e3db44
          name: container-image
